{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1aa77dc5_bdee6de8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 17685
      },
      "writtenOn": "2025-05-19T08:02:51Z",
      "side": 1,
      "message": "recheck - neutron-linuxbridge-tempest failed why fetching get-pip.py, however the file is reachable... probably pypa.io glitch :S",
      "revId": "9b875bad906dbb70b10fea585efc89091eef9519",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "d26d12ad_ca949cbc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 17685
      },
      "writtenOn": "2025-05-19T10:18:08Z",
      "side": 1,
      "message": "False Code-Review-1 from \"Software Factory\" 3rd party CI: upstream zuul does not complain about it and there is no such zuul config error [1] at the moment.\n\nBesides, this trivial fix makes devstack to be able to deploy, and this is needed to unblock xena gate, so fast-approving.\n\n[1] https://zuul.opendev.org/t/openstack/config-errors?branch\u003dunmaintained%2Fxena\u0026skip\u003d0",
      "revId": "9b875bad906dbb70b10fea585efc89091eef9519",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}