{
  "comments": [
    {
      "key": {
        "uuid": "9a8ffd7b_22ed6925",
        "filename": "lib/cinder",
        "patchSetId": 1
      },
      "lineNbr": 238,
      "author": {
        "id": 7350
      },
      "writtenOn": "2015-11-25T16:14:48Z",
      "side": 1,
      "message": "Line 236 is supposed to create the directory with the correct permission. I think you have another issue in your setup, thus this fix will likely not help you much.",
      "revId": "ab1c09e636a023441926efb51bd1536b88611675",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}