{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "9af26cb5_53b9432b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 8556
      },
      "writtenOn": "2022-06-02T23:19:11Z",
      "side": 1,
      "message": "this fixes the grenade job as we can see that is passing in this patch.\nfailure can be seen in another devstack stable/wallaby patch - https://review.opendev.org/c/openstack/devstack/+/838091\n\n+2 from me, I just rebased the patch.",
      "revId": "e2bed1b72fcac3b689951372e4ac33784736c9aa",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0700a6f1_cac30947",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5314
      },
      "writtenOn": "2022-06-03T15:51:48Z",
      "side": 1,
      "message": "recheck nova-ceph-multistore oom_reaper killed mysqld and i think that\u0027s what caused the failures; available swap was at zero",
      "revId": "e2bed1b72fcac3b689951372e4ac33784736c9aa",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c878f7fd_27dd2c84",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5314
      },
      "writtenOn": "2022-06-03T19:24:52Z",
      "side": 1,
      "message": "nova-ceph-multistore failed again, but this time it was a POST_FAILURE ... all the tests ran and passed, it was an rsync failure during fetch-output",
      "revId": "e2bed1b72fcac3b689951372e4ac33784736c9aa",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "a4512f95_6adb9743",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5314
      },
      "writtenOn": "2022-06-03T19:26:00Z",
      "side": 1,
      "message": "recheck nova-ceph-multistore POST_FAILURE",
      "revId": "e2bed1b72fcac3b689951372e4ac33784736c9aa",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0d6b13d5_06665595",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 8556
      },
      "writtenOn": "2022-06-04T01:35:47Z",
      "side": 1,
      "message": "recheck seems pypi indexing issue?\n\nThe conflict is caused by:\n    keystonemiddleware 9.2.0 depends on oslo.utils\u003e\u003d3.33.0\n    The user requested (constraint) oslo-utils\u003d\u003d\u003d4.8.2",
      "revId": "e2bed1b72fcac3b689951372e4ac33784736c9aa",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}